### ISSUE TITLE
merge with djoos/Symfony2-coding-standard

### ISSUE THREAD

**Issue by mmoll** [xalopp/symfony-coding-standard#9]
https://github.com/djoos/Symfony2-coding-standard seems to be the new hot thing regarding Symfony coding standards. If anything is missing there it should get pulled from here and then the one from djoos can get included in MO4.

**Comment by xalopp** [comment]
Sounds like a plan! As far as I can see, it's missing autofixing, so it can definitely benefit from our work here.

**Comment by SebTM** [comment]
@xalopp @ritters Hey, I would like to make pull-requests to the djoos-projects for this issue. Is it ok for you, that I use your code for this, I will mention you in PR?

**Comment by mmoll** [comment]
this was abandoned.
